### ISSUE TITLE
Global component doesn't work with babel plugin

### ISSUE THREAD

**Issue by alidcast** [emotion-js/next#9]
Adding emotion's babel plugin interferes with global styles added via `Global` component.

In the documentation, it says babel isn't needed but console warned that it's still needed to use styled components as selectors.

I see that this repo has it's babel plugin, but I'm guessing it's not yet documented for a reason.

How should we go about this? 

Thanks

**Comment by alidcastano** [comment]
Using `injectGlobal` and `babel-plugin-emotion` works as a workaround but not sure if it's recommended to mix in these emotion packages

**Comment by mitchellhamilton** [comment]
Sorry, I just copied the error from the other repo but I meant that @emotion/babel-plugin-core is required for component selectors.

Using babel-plugin-emotion with the packages in this repo will not work.
